version: '2'

services:

### Nginx Server Container ##################################

    nginx:
        build: ./nginx
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "8080:80"
        links:
            - php

### PHP Container ###########################################

    php:
        build: ./php
        volumes:
            - ../:/var/www/laravel
            - ./logs/php/:/usr/local/var/log
        expose:
            - "9000"

### DATA Container ##########################################

    data:
        build: ./data
        volumes:
            - /var/lib/postgres


### PostgreSQL Container ####################################

    postgres:
        build: ./postgres
        volumes_from:
            - data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: bizmerk
            POSTGRES_USER: bizmerk
            POSTGRES_PASSWORD: bizmerk
        links:
            - php
